name: zap
on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    env:
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Subtitute Password
        working-directory: ./testing/zap
        run: |
          echo Path: $(pwd)
          LOCAL_VAR=$(echo 'cypressidir$CYPRESS_PW' | base64)
          sed -i 's/@pw@/'$LOCAL_VAR'/g' dev.context
      - name: Copy Context
        run: |
          echo Paths from root: $(ls /home/runner/work)
          cp /home/runner/work/biohubbc/biohubbc/testing/zap/dev.context /home/runner/work/zap/wrk
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://dev-biohubbc.apps.silver.devops.gov.bc.ca/'
          cmd_options: '-a -n dev.context'  
