name: zap
on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    env:
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Subtitute Password
        working-directory: ./testing/zap
        run:
          echo ${{env.working-directory}}
          LOCAL_VAR=$(echo 'cypressidir$CYPRESS_PW' | base64)
          sed -i 's/@pw@/'$LOCAL_VAR'/g' dev.context
          pwd
      - name: Copy context
        run:
          echo ${{env.working-directory}}
          cd /
          find -name dev.context
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://dev-biohubbc.apps.silver.devops.gov.bc.ca/'
          cmd_options: '-a -n ./testing/zap/dev.context'
